language: ruby
sudo: required
rvm:
  - 2.6.1
before_script:
  - bundle exec rails assets:precompile
  - bundle exec rails db:create --all
  - bundle exec rails db:migrate
script:
  - bundle exec rspec
services:
  - postgresql
addons:
  postgresql: "9.4"
  chrome: stable
